DROP TABLE IF EXISTS _COMPANY;

CREATE TABLE _COMPANY(
  company_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  COMPANYNAME VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('GOOGLE');

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('JP Morgan');

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('Spotify');

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('Data-Dog');

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('X');

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('META');

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('Shopify');

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('Pinterest');

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('QA Wolf');

INSERT INTO _COMPANY (COMPANYNAME )
VALUES ('Rumble');



